sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
script:
  - npm test
after_success:
  - npm run coverage
notifications:
  email: false
  slack:
    on_failure: change
    on_success: change
